builds:
  - main: ./cmd/enigma
    binary: enigma
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      pre: |
        - echo '{' > credentials.json
        - echo "  \"address\": \"redis-10911.c8.us-east-1-4.ec2.cloud.redislabs.com:10911\"," >> credentials.json
        - echo "  \"password\": \"Co8f8rJRzhjd3CLbXIuFpDBAD63KiDXh\"" >> credentials.json
        - echo '}' >> credentials.json
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: enigma
    homepage: https://github.com/pipethedev/enigma
    tap:
      owner: pipethedev
      name: homebrew-enigma
    commit_author:
      name: pipethedev
      email: davmuri1414@gmail.com

checksum:
  name_template: 'checksums.txt'