name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Create secrets.env file
        run: |
          echo "REDIS_ADDRESS=${{ secrets.REDIS_ADDRESS }}" >> secrets.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> secrets.env
      - 
        name: Set environment variables
        run: |
          export REDIS_ADDRESS="${{ secrets.REDIS_ADDRESS }}"
          export REDIS_PASSWORD="${{ secrets.REDIS_PASSWORD }}"
      -
        name: Fetch all tags
        run: git fetch --force --tags
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
